CLASSES:
- hand
- salad
- steak
- whiskey
- book
DATA_FORMAT: NCHW
IMAGE_SIZE:
- 128
- 128
POST_PROCESSOR:
- FormatYoloV2:
    anchors:
    - - 1.3221
      - 1.73145
    - - 3.19275
      - 4.00944
    - - 5.05587
      - 8.09892
    - - 9.47112
      - 4.84053
    - - 11.2364
      - 10.0071
    boxes_per_cell: 5
    data_format: NCHW
    image_size:
    - 128
    - 128
    num_classes: 5
- ExcludeLowScoreBox:
    threshold: 0.05
- NMS:
    classes:
    - hand
    - salad
    - steak
    - whiskey
    - book
    iou_threshold: 0.5
    max_output_size: 100
    per_class: true
PRE_PROCESSOR:
- ResizeWithGtBoxes:
    size:
    - 128
    - 128
- DivideBy255: null
TASK: IMAGE.OBJECT_DETECTION
