BATCH_SIZE: 16
CLASSES:
- Humanface
DATASET:
  AUGMENTOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.data_augmentor.Brightness
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.Color
      max_value: 1.25
      min_value: 0.75
    - !!python/object:lmnet.data_augmentor.FlipLeftRight
      probability: 0.5
    - !!python/object:lmnet.data_augmentor.Hue
      max_value: 10
      min_value: -10
    - !!python/object:lmnet.data_augmentor.SSDRandomCrop
      aspect_ratio_max: 2
      aspect_ratio_min: 0.5
      min_crop_ratio: 0.3
      sample_options: !!python/tuple
      - null
      - !!python/tuple
        - 0.1
        - null
      - !!python/tuple
        - 0.3
        - null
      - !!python/tuple
        - 0.7
        - null
      - !!python/tuple
        - 0.9
        - null
      - !!python/tuple
        - null
        - null
  BATCH_SIZE: 16
  DATA_FORMAT: NHWC
  PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
    processors:
    - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
      size:
      - 224
      - 224
    - !!python/object:lmnet.pre_processor.PerImageStandardization {}
DATASET_CLASS: !!python/name:lmnet.datasets.open_images_v4.OpenImagesV4BoundingBoxBase ''
DATA_FORMAT: NHWC
IMAGE_SIZE:
- 224
- 224
IS_DEBUG: false
IS_PRETRAIN: false
KEEP_CHECKPOINT_MAX: 5
MAX_EPOCHS: 1000
NETWORK:
  ACTIVATION_QUANTIZER: !!python/name:lmnet.quantizations.linear.linear_mid_tread_half_quantizer ''
  ACTIVATION_QUANTIZER_KWARGS:
    bit: 2
    max_value: 2.0
  ANCHORS:
  - !!python/tuple
    - 1.3221
    - 1.73145
  - !!python/tuple
    - 3.19275
    - 4.00944
  - !!python/tuple
    - 5.05587
    - 8.09892
  - !!python/tuple
    - 9.47112
    - 4.84053
  - !!python/tuple
    - 11.2364
    - 10.0071
  BATCH_SIZE: 16
  CLASS_SCALE: 1.0
  COORDINATE_SCALE: 1.0
  DATA_FORMAT: NHWC
  IMAGE_SIZE:
  - 224
  - 224
  LEARNING_RATE_FUNC: null
  LEARNING_RATE_KWARGS: null
  LOSS_IOU_THRESHOLD: 0.6
  LOSS_WARMUP_STEPS: 500
  NMS_IOU_THRESHOLD: 0.5
  NMS_MAX_OUTPUT_SIZE: 100
  NO_OBJECT_SCALE: 1.0
  OBJECT_SCALE: 5.0
  OPTIMIZER_CLASS: !!python/name:tensorflow.python.training.adam.AdamOptimizer ''
  OPTIMIZER_KWARGS:
    learning_rate: 0.001
  QUANTIZE_FIRST_CONVOLUTION: true
  QUANTIZE_LAST_CONVOLUTION: false
  SCORE_THRESHOLD: 0.05
  WEIGHT_DECAY_RATE: 0.0005
  WEIGHT_QUANTIZER: !!python/name:lmnet.quantizations.binary.binary_channel_wise_mean_scaling_quantizer ''
  WEIGHT_QUANTIZER_KWARGS: {}
NETWORK_CLASS: !!python/name:lmnet.networks.object_detection.lm_fyolo.LMFYoloQuantize ''
NMS: !!python/name:lmnet.post_processor.NMS ''
POST_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.post_processor.FormatYoloV2
    anchors:
    - !!python/tuple
      - 1.3221
      - 1.73145
    - !!python/tuple
      - 3.19275
      - 4.00944
    - !!python/tuple
      - 5.05587
      - 8.09892
    - !!python/tuple
      - 9.47112
      - 4.84053
    - !!python/tuple
      - 11.2364
      - 10.0071
    boxes_per_cell: 5
    data_format: NHWC
    image_size:
    - 224
    - 224
    num_classes: 1
  - !!python/object:lmnet.post_processor.ExcludeLowScoreBox
    threshold: 0.05
  - !!python/object:lmnet.post_processor.NMS
    classes:
    - Humanface
    iou_threshold: 0.5
    max_output_size: 100
    per_class: true
PRETRAIN_DIR: ''
PRETRAIN_FILE: ''
PRETRAIN_VARS: []
PRE_PROCESSOR: !!python/object:lmnet.data_processor.Sequence
  processors:
  - !!python/object:lmnet.pre_processor.ResizeWithGtBoxes
    size:
    - 224
    - 224
  - !!python/object:lmnet.pre_processor.PerImageStandardization {}
SAVE_CHECKPOINT_STEPS: 1000
SUMMARISE_STEPS: 100
TASK: !!python/object/apply:lmnet.common.Tasks
- IMAGE.OBJECT_DETECTION
TEST_STEPS: 1000
